AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates IAM Users, Groups, and a temporary password in Secrets Manager
  for a lab on automated IAM resource provisioning.

Resources:
  UserPasswordSecretBenedict:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: 'Temporary password for IAM users'
      GenerateSecretString:
        PasswordLength: 16
        ExcludePunctuation: true

  EC2UserGroupBenedict:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: EC2GroupBenedict
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess'

  S3UserGroupBenedict:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: S3GroupBenedict
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'

  EC2UserBenedict:
    Type: 'AWS::IAM::User'
    DependsOn:
      - UserPasswordSecretBenedict
      - EC2UserGroupBenedict
    Properties:
      UserName: ec2-user-benedict
      Groups:
        - !Ref EC2UserGroupBenedict
      LoginProfile:
        # Use the Fn::Sub on the secret ARN to resolve the password
        Password: !Sub '{{resolve:secretsmanager:${UserPasswordSecretBenedict}}}'
        PasswordResetRequired: true

  S3UserBenedict:
    Type: 'AWS::IAM::User'
    DependsOn:
      - UserPasswordSecretBenedict
      - S3UserGroupBenedict
    Properties:
      UserName: s3-user-benedict
      Groups:
        - !Ref S3UserGroupBenedict
      LoginProfile:
        # Use the Fn::Sub on the secret ARN to resolve the password
        Password: !Sub '{{resolve:secretsmanager:${UserPasswordSecretBenedict}}}'
        PasswordResetRequired: true
